import asyncio
from telethon.tl import functions, types
from telethon.sync import TelegramClient ,events 
api_id = 4091096
api_hash = '6bb0682b4af56456201c3b9d8b99c94a'
bot_token = '2025919134:AAEiMUp8gZ3W2QD-YAgDpGZXcYol_RfEPWg'
STRING_SESSION = "BQB9PmJnn8EwkJ6MuyAZExB6-Z2zzAOBZ6Ltb7_bKSaIyUQKsCxi15oX98Qe_6gYpD9d45CgxFK1nDM2efta-V4h0Keo0ahhTB0hMgQnps7iV6P5NCaKNCvsbZglLEtI3jmEvZ_TeFY7vkHKJoWpS5BvnJy2ZJg-DY71SCWrs92PFT3oZVouSSVi15mqq17G6Ae4tf1y8wApUrd0jz5XOQu9DEa12X6reKXDo70JUIVaVaWAQWkRjUbPWJT0K1eCjD-s_2pxisZtpbtQf9SqEA3SNy8_3shknWNQYD5Lp7IsYo7iWNymW8CgFMZSeAJNYOkaBRHDpC-PneMy7DyRs9yRAAAAAHR9PgwA"

# We have to manually call "start" if we want an explicit bot token
tbot = TelegramClient('bot', api_id, api_hash).start(bot_token=bot_token)
ubot = TelegramClient('anon',StringSession(STRING_SESSION), api_id, api_hash)


with tbot:
  @tbot.on(events.NewMessage(pattern="^/cc (.*)"))
  async def alive(event):
    if event.is_group:
        if await is_register_admin(event.input_chat, event.message.sender_id):
            pass
        else:
            return
    sender = await event.get_sender()
    fname = sender.first_name
    m = await event.reply("Generating CC...Pls Weit.")
    ok = event.pattern_match.group(1)
    async with ubot.conversation("@ccgen_robot") as bot_conv:
        await bot_conv.send_message("/generate")
        await bot_conv.send_message("💳Credit Card Generator💳")
        await asyncio.sleep(2)
        await bot_conv.send_message(ok)
        await asyncio.sleep(1)
        response = await bot_conv.get_response()
        await asyncio.sleep(1)
        await response.click(text="✅Generate✅")
        await asyncio.sleep(2)
        text = "****Generated Cards:****\n"
        gen = await bot_conv.get_response()
        card = gen.text
        text = f"{card.splitlines()[0]}\n"
        text += f"{card.splitlines()[1]}\n"
        text += f"{card.splitlines()[2]}\n"
        text += f"{card.splitlines()[3]}\n"
        text += f"{card.splitlines()[4]}\n"
        text += f"{card.splitlines()[5]}\n"
        text += f"\nGenerated By: **{fname}**"
        await m.edit(text)

tbot.start()
tbot.run_until_disconnected()











